version: '3.4'

services:
  piapi:
    image: piapi
    container_name: piapi
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      HUE_USER: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      HUE_IP: XXX.XXX.X.XX
      HUE_ADDR: XXX.XXX.X.XX
      SONOS_API_IP: XXX.XXX.X.XX:XXXX
    network_mode: host
    restart: always
    ports:
      - 5015:5015