version: '3.4'

services:
  piapi:
    image: piapi
    container_name: piapi
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      HUE_USER: ${HUE_USER}
      HUE_HUB_IP: ${HUE_HUB_IP}
      SONOS_API_IP: ${SONOS_API_IP}
    network_mode: host
    restart: always
    ports:
      - 5015:5015